<?php  use VuFind\Search\Solr\Results;

?>
<?php if ($this->results instanceof Results): ?>
    <?php if ($this->params->getSearchClassId() == 'Solr' && $this->collapseExpandConfig->isEnabled()): ?>
        <form class="form-inline search-collapse-expand" action="<?= $this->currentPath() ?>"
            method="POST" id="collapse-expand-form">
            <div class="form-group">
                <label for="collapse-expand-checkbox"><?= $this->transEsc('collapse results') ?></label>
                <input type="checkbox" name="collapse-expand-enabled" value=""
                    id="collapse-expand-checkbox"
                    <?php if ($this->collapseExpandConfig->isActive()): ?>checked<?php endif; ?>/>
            </div>
            <noscript>
                <p>Please enable JavaScript</p>
            </noscript>
        </form>
    <?php endif; ?>
<?php endif; ?>
